/**
 * Unity Export - Full Package Generation
 *
 * Generates complete Unity-ready packages including:
 * - Audio files organized by type
 * - C# AudioManager script
 * - ScriptableObject assets
 * - Event system integration
 */

import type { StemBundle } from "../stemGenerator";
import type { GameState } from "../gameStateEngine";

// ==================== Unity Package Types ====================

export interface UnityPackage {
  manifest: UnityManifest;
  audioManager: string;
  scriptableObjects: Map<string, string>;
  eventDefinitions: string;
  editorScript: string;
  readme: string;
}

export interface UnityManifest {
  name: string;
  version: string;
  unity: string;
  generator: string;
  generatedAt: string;
  bundles: UnityBundleInfo[];
}

export interface UnityBundleInfo {
  id: string;
  name: string;
  gameState: GameState;
  stemCount: number;
  bpm: number;
  duration: number;
}

// ==================== AudioManager Generation ====================

/**
 * Generate a full-featured AudioManager for Unity
 */
export function generateUnityAudioManager(
  bundles: StemBundle[],
  projectName: string = "SwanbladeAudio"
): string {
  const stateEnumValues = [...new Set(bundles.map((b) => toPascalCase(b.gameState)))];

  return `using UnityEngine;
using UnityEngine.Audio;
using System;
using System.Collections;
using System.Collections.Generic;

namespace ${projectName}
{
    /// <summary>
    /// Swanblade Audio Manager - Controls game state-driven audio playback
    /// Auto-generated by Swanblade
    /// </summary>
    public class SwanbladeAudioManager : MonoBehaviour
    {
        public static SwanbladeAudioManager Instance { get; private set; }

        [Header("Configuration")]
        [SerializeField] private AudioMixerGroup masterMixerGroup;
        [SerializeField] private float crossfadeDuration = 1.5f;
        [SerializeField] private float stemFadeSpeed = 0.5f;

        [Header("Audio Bundles")]
${bundles.map((b) => `        [SerializeField] private ${toPascalCase(b.gameState)}AudioBundle ${b.gameState}Bundle;`).join("\n")}

        [Header("Runtime State")]
        [SerializeField] private GameAudioState currentState = GameAudioState.Menu;

        // Stem audio sources
        private Dictionary<string, AudioSource> activeStemSources = new Dictionary<string, AudioSource>();
        private Dictionary<string, float> stemTargetVolumes = new Dictionary<string, float>();

        // Crossfade state
        private Coroutine crossfadeCoroutine;
        private float globalMusicVolume = 1f;

        public event Action<GameAudioState> OnStateChanged;

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }

            Instance = this;
            DontDestroyOnLoad(gameObject);
            InitializeAudioSources();
        }

        private void InitializeAudioSources()
        {
            // Create audio sources for each stem type
            string[] stemTypes = { "drums", "bass", "melody", "harmony", "atmosphere", "fx", "vocals" };

            foreach (var stemType in stemTypes)
            {
                var go = new GameObject($"Stem_{stemType}");
                go.transform.SetParent(transform);

                var source = go.AddComponent<AudioSource>();
                source.outputAudioMixerGroup = masterMixerGroup;
                source.loop = true;
                source.playOnAwake = false;
                source.volume = 0f;

                activeStemSources[stemType] = source;
                stemTargetVolumes[stemType] = 0f;
            }
        }

        /// <summary>
        /// Transition to a new game audio state with crossfade
        /// </summary>
        public void SetGameState(GameAudioState newState)
        {
            if (currentState == newState) return;

            var previousState = currentState;
            currentState = newState;

            if (crossfadeCoroutine != null)
            {
                StopCoroutine(crossfadeCoroutine);
            }

            crossfadeCoroutine = StartCoroutine(CrossfadeToState(newState));
            OnStateChanged?.Invoke(newState);

            Debug.Log($"[SwanbladeAudio] State change: {previousState} -> {newState}");
        }

        private IEnumerator CrossfadeToState(GameAudioState state)
        {
            var bundle = GetBundleForState(state);
            if (bundle == null)
            {
                Debug.LogWarning($"[SwanbladeAudio] No bundle found for state: {state}");
                yield break;
            }

            // Get stems from bundle
            var stems = bundle.GetAllStems();
            var stemTypes = GetStemTypesForBundle(bundle);

            // Fade out all current stems
            foreach (var kvp in stemTargetVolumes)
            {
                stemTargetVolumes[kvp.Key] = 0f;
            }

            // Wait for partial fadeout
            yield return new WaitForSeconds(crossfadeDuration * 0.5f);

            // Load new clips and start playback
            for (int i = 0; i < stems.Length && i < stemTypes.Length; i++)
            {
                var clip = stems[i];
                var type = stemTypes[i];

                if (clip != null && activeStemSources.TryGetValue(type, out var source))
                {
                    source.clip = clip;
                    source.time = 0f;
                    source.Play();
                    stemTargetVolumes[type] = 1f;
                }
            }

            // Complete crossfade
            yield return new WaitForSeconds(crossfadeDuration * 0.5f);
        }

        private void Update()
        {
            // Smooth volume transitions
            foreach (var kvp in activeStemSources)
            {
                var source = kvp.Value;
                var targetVolume = stemTargetVolumes.GetValueOrDefault(kvp.Key, 0f) * globalMusicVolume;

                source.volume = Mathf.MoveTowards(source.volume, targetVolume, stemFadeSpeed * Time.deltaTime);

                // Stop playback when faded out
                if (source.volume < 0.01f && source.isPlaying && targetVolume == 0f)
                {
                    source.Stop();
                }
            }
        }

        /// <summary>
        /// Dynamically adjust individual stem volume (0-1)
        /// </summary>
        public void SetStemVolume(string stemType, float volume)
        {
            if (stemTargetVolumes.ContainsKey(stemType))
            {
                stemTargetVolumes[stemType] = Mathf.Clamp01(volume);
            }
        }

        /// <summary>
        /// Set master music volume (0-1)
        /// </summary>
        public void SetMasterVolume(float volume)
        {
            globalMusicVolume = Mathf.Clamp01(volume);
        }

        /// <summary>
        /// Get the current game audio state
        /// </summary>
        public GameAudioState GetCurrentState() => currentState;

        /// <summary>
        /// Get the current BPM from active bundle
        /// </summary>
        public float GetCurrentBPM()
        {
            var bundle = GetBundleForState(currentState);
            return bundle?.bpm ?? 120f;
        }

        /// <summary>
        /// Check if a specific stem is currently playing
        /// </summary>
        public bool IsStemPlaying(string stemType)
        {
            return activeStemSources.TryGetValue(stemType, out var source) && source.isPlaying;
        }

        private SwanbladeAudioBundleBase GetBundleForState(GameAudioState state)
        {
            return state switch
            {
${bundles.map((b) => `                GameAudioState.${toPascalCase(b.gameState)} => ${b.gameState}Bundle,`).join("\n")}
                _ => null
            };
        }

        private string[] GetStemTypesForBundle(SwanbladeAudioBundleBase bundle)
        {
            // Return stem types in order they appear in the bundle
            var types = new List<string>();
            var clips = bundle.GetAllStems();

            // Match with standard stem order
            string[] standardOrder = { "drums", "bass", "melody", "harmony", "atmosphere", "fx", "vocals" };

            foreach (var type in standardOrder)
            {
                if (HasStemOfType(bundle, type))
                {
                    types.Add(type);
                }
            }

            return types.ToArray();
        }

        private bool HasStemOfType(SwanbladeAudioBundleBase bundle, string type)
        {
            // Check if bundle has a stem of this type
            return bundle.GetStemsByRole(GetRoleForType(type)).Length > 0;
        }

        private string GetRoleForType(string type)
        {
            return type switch
            {
                "drums" or "bass" => "foundation",
                "melody" or "vocals" => "accent",
                "harmony" or "atmosphere" => "atmosphere",
                "fx" => "transition",
                _ => "accent"
            };
        }
    }

    /// <summary>
    /// Game audio states matching Swanblade game states
    /// </summary>
    public enum GameAudioState
    {
        ${stateEnumValues.join(",\n        ")}
    }

    /// <summary>
    /// Base class for audio bundles
    /// </summary>
    public abstract class SwanbladeAudioBundleBase : ScriptableObject
    {
        public abstract AudioClip[] GetAllStems();
        public abstract AudioClip[] GetStemsByRole(string role);
        public abstract float bpm { get; }
    }
}
`;
}

// ==================== Event Definitions ====================

/**
 * Generate Unity event definitions for audio triggers
 */
export function generateUnityEventDefinitions(
  bundles: StemBundle[],
  projectName: string = "SwanbladeAudio"
): string {
  return `using UnityEngine;
using UnityEngine.Events;

namespace ${projectName}
{
    /// <summary>
    /// Audio events for game integration
    /// </summary>
    [CreateAssetMenu(fileName = "AudioEvents", menuName = "Swanblade/Audio Events")]
    public class SwanbladeAudioEvents : ScriptableObject
    {
        [Header("State Change Events")]
        public UnityEvent<GameAudioState> OnStateChangeRequested;
        public UnityEvent<GameAudioState, GameAudioState> OnStateChanged;

        [Header("Playback Events")]
        public UnityEvent OnBeatHit;
        public UnityEvent OnBarStart;
        public UnityEvent<float> OnIntensityChange;

        [Header("Stem Events")]
        public UnityEvent<string, float> OnStemVolumeChange;
        public UnityEvent<string> OnStemMuted;
        public UnityEvent<string> OnStemUnmuted;

        /// <summary>
        /// Request a state change through the event system
        /// </summary>
        public void RequestStateChange(GameAudioState newState)
        {
            OnStateChangeRequested?.Invoke(newState);
        }

        /// <summary>
        /// Request a state change by string name
        /// </summary>
        public void RequestStateChangeByName(string stateName)
        {
            if (System.Enum.TryParse<GameAudioState>(stateName, true, out var state))
            {
                RequestStateChange(state);
            }
            else
            {
                Debug.LogWarning($"Unknown audio state: {stateName}");
            }
        }
    }

    /// <summary>
    /// Component for triggering audio state changes from Unity events
    /// </summary>
    public class SwanbladeAudioTrigger : MonoBehaviour
    {
        [SerializeField] private GameAudioState targetState;
        [SerializeField] private bool triggerOnStart = false;
        [SerializeField] private bool triggerOnEnable = false;

        private void Start()
        {
            if (triggerOnStart)
            {
                TriggerStateChange();
            }
        }

        private void OnEnable()
        {
            if (triggerOnEnable && !triggerOnStart)
            {
                TriggerStateChange();
            }
        }

        public void TriggerStateChange()
        {
            SwanbladeAudioManager.Instance?.SetGameState(targetState);
        }

        public void TriggerStateChange(int stateIndex)
        {
            if (System.Enum.IsDefined(typeof(GameAudioState), stateIndex))
            {
                SwanbladeAudioManager.Instance?.SetGameState((GameAudioState)stateIndex);
            }
        }
    }

    /// <summary>
    /// Component for controlling stem volumes based on gameplay
    /// </summary>
    public class SwanbladeStemController : MonoBehaviour
    {
        [SerializeField] private string stemType = "drums";
        [SerializeField] private bool linkToParameter = false;
        [SerializeField] private string parameterName = "Health";

        private float cachedVolume = 1f;

        public void SetVolume(float volume)
        {
            cachedVolume = Mathf.Clamp01(volume);
            SwanbladeAudioManager.Instance?.SetStemVolume(stemType, cachedVolume);
        }

        public void Mute()
        {
            SwanbladeAudioManager.Instance?.SetStemVolume(stemType, 0f);
        }

        public void Unmute()
        {
            SwanbladeAudioManager.Instance?.SetStemVolume(stemType, cachedVolume);
        }
    }
}
`;
}

// ==================== Editor Script ====================

/**
 * Generate Unity editor script for bundle management
 */
export function generateUnityEditorScript(
  projectName: string = "SwanbladeAudio"
): string {
  return `#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using System.IO;

namespace ${projectName}.Editor
{
    /// <summary>
    /// Editor utilities for Swanblade audio bundles
    /// </summary>
    public class SwanbladeAudioEditor : EditorWindow
    {
        [MenuItem("Tools/Swanblade/Audio Manager")]
        public static void ShowWindow()
        {
            GetWindow<SwanbladeAudioEditor>("Swanblade Audio");
        }

        private void OnGUI()
        {
            GUILayout.Label("Swanblade Audio Manager", EditorStyles.boldLabel);
            EditorGUILayout.Space();

            if (GUILayout.Button("Create Audio Manager Prefab"))
            {
                CreateAudioManagerPrefab();
            }

            EditorGUILayout.Space();

            if (GUILayout.Button("Import Audio Bundle"))
            {
                ImportAudioBundle();
            }

            EditorGUILayout.Space();
            EditorGUILayout.HelpBox(
                "Use Import Audio Bundle to import .swanblade packages exported from the Swanblade web app.",
                MessageType.Info
            );
        }

        private void CreateAudioManagerPrefab()
        {
            var go = new GameObject("SwanbladeAudioManager");
            go.AddComponent<SwanbladeAudioManager>();

            // Ensure directory exists
            var prefabPath = "Assets/Swanblade/Prefabs";
            if (!AssetDatabase.IsValidFolder(prefabPath))
            {
                Directory.CreateDirectory(prefabPath);
                AssetDatabase.Refresh();
            }

            // Save prefab
            var path = $"{prefabPath}/SwanbladeAudioManager.prefab";
            PrefabUtility.SaveAsPrefabAsset(go, path);
            DestroyImmediate(go);

            EditorUtility.DisplayDialog("Success", $"Audio Manager prefab created at {path}", "OK");
        }

        private void ImportAudioBundle()
        {
            var path = EditorUtility.OpenFilePanel("Select Swanblade Bundle", "", "zip,swanblade");
            if (string.IsNullOrEmpty(path)) return;

            // TODO: Implement bundle import logic
            EditorUtility.DisplayDialog("Import", $"Would import bundle from: {path}", "OK");
        }
    }

    /// <summary>
    /// Custom inspector for audio bundles
    /// </summary>
    [CustomEditor(typeof(SwanbladeAudioBundleBase), true)]
    public class SwanbladeAudioBundleEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();

            EditorGUILayout.Space();

            var bundle = target as SwanbladeAudioBundleBase;
            if (bundle != null)
            {
                EditorGUILayout.LabelField("Bundle Info", EditorStyles.boldLabel);
                EditorGUILayout.LabelField("BPM", bundle.bpm.ToString());
                EditorGUILayout.LabelField("Stems", bundle.GetAllStems().Length.ToString());

                if (GUILayout.Button("Preview All Stems"))
                {
                    PreviewStems(bundle);
                }
            }
        }

        private void PreviewStems(SwanbladeAudioBundleBase bundle)
        {
            foreach (var clip in bundle.GetAllStems())
            {
                if (clip != null)
                {
                    // Play preview (editor-only)
                    var method = typeof(AudioImporter).Assembly
                        .GetType("UnityEditor.AudioUtil")
                        .GetMethod("PlayPreviewClip");

                    if (method != null)
                    {
                        method.Invoke(null, new object[] { clip, 0, false });
                        break; // Play first clip only for preview
                    }
                }
            }
        }
    }
}
#endif
`;
}

// ==================== README ====================

/**
 * Generate README for Unity package
 */
export function generateUnityReadme(
  bundles: StemBundle[],
  projectName: string = "SwanbladeAudio"
): string {
  return `# ${projectName} - Swanblade Audio Package

## Overview

This Unity package was generated by Swanblade and contains:
- ${bundles.length} audio bundle(s) for different game states
- SwanbladeAudioManager script for state-driven playback
- Event system for game integration
- Editor tools for bundle management

## Quick Start

1. **Import the package** into your Unity project
2. **Add the SwanbladeAudioManager** prefab to your scene
3. **Call SetGameState()** to trigger audio transitions

\`\`\`csharp
// Example: Change to combat music
SwanbladeAudioManager.Instance.SetGameState(GameAudioState.Combat);

// Example: Adjust stem volume
SwanbladeAudioManager.Instance.SetStemVolume("drums", 0.8f);
\`\`\`

## Audio Bundles

${bundles.map((b) => `- **${b.name}** (${b.gameState}): ${b.stems.length} stems, ${b.manifest.bpm} BPM, ${b.manifest.duration}s`).join("\n")}

## Integration

### Via Script
\`\`\`csharp
using ${projectName};

public class GameManager : MonoBehaviour
{
    void OnEnterCombat()
    {
        SwanbladeAudioManager.Instance.SetGameState(GameAudioState.Combat);
    }

    void UpdatePlayerHealth(float health)
    {
        // Lower drums as health decreases
        SwanbladeAudioManager.Instance.SetStemVolume("drums", health);
    }
}
\`\`\`

### Via Events
Attach \`SwanbladeAudioTrigger\` to game objects and configure in the inspector.

## Provenance

All audio in this package has verifiable provenance through the o8 protocol.
Verify at: https://verify.o8.audio

---
Generated by Swanblade | https://swanblade.io
`;
}

// ==================== Full Package Generation ====================

/**
 * Generate complete Unity package
 */
export function generateUnityPackage(
  bundles: StemBundle[],
  projectName: string = "SwanbladeAudio"
): UnityPackage {
  const manifest: UnityManifest = {
    name: projectName,
    version: "1.0.0",
    unity: "2021.3",
    generator: "swanblade",
    generatedAt: new Date().toISOString(),
    bundles: bundles.map((b) => ({
      id: b.id,
      name: b.name,
      gameState: b.gameState,
      stemCount: b.stems.length,
      bpm: b.manifest.bpm,
      duration: b.manifest.duration,
    })),
  };

  // Generate ScriptableObjects for each bundle
  const scriptableObjects = new Map<string, string>();
  for (const bundle of bundles) {
    const className = `${toPascalCase(bundle.gameState)}AudioBundle`;
    scriptableObjects.set(
      `${className}.cs`,
      generateBundleScriptableObject(bundle, projectName)
    );
  }

  return {
    manifest,
    audioManager: generateUnityAudioManager(bundles, projectName),
    scriptableObjects,
    eventDefinitions: generateUnityEventDefinitions(bundles, projectName),
    editorScript: generateUnityEditorScript(projectName),
    readme: generateUnityReadme(bundles, projectName),
  };
}

/**
 * Generate ScriptableObject class for a specific bundle
 */
function generateBundleScriptableObject(
  bundle: StemBundle,
  projectName: string
): string {
  const className = `${toPascalCase(bundle.gameState)}AudioBundle`;

  return `using UnityEngine;

namespace ${projectName}
{
    /// <summary>
    /// Audio bundle for ${bundle.gameState} game state
    /// Generated by Swanblade on ${bundle.createdAt}
    /// </summary>
    [CreateAssetMenu(fileName = "${bundle.name}", menuName = "Swanblade/Bundles/${className}")]
    public class ${className} : SwanbladeAudioBundleBase
    {
        [Header("Bundle Info")]
        public string bundleId = "${bundle.id}";
        public string gameState = "${bundle.gameState}";
        [SerializeField] private float _bpm = ${bundle.manifest.bpm}f;
        public string musicalKey = "${bundle.manifest.key}";
        public float duration = ${bundle.manifest.duration}f;

        public override float bpm => _bpm;

        [Header("Stems")]
${bundle.stems.map((stem) => `        public AudioClip ${stem.stemType}Stem;`).join("\n")}

        [Header("Provenance")]
        public string provenanceTimestamp = "${bundle.manifest.provenance.timestamp}";
${bundle.manifest.provenance.identityId ? `        public string identityId = "${bundle.manifest.provenance.identityId}";` : ""}

        public override AudioClip[] GetAllStems()
        {
            return new AudioClip[] { ${bundle.stems.map((s) => `${s.stemType}Stem`).join(", ")} };
        }

        public override AudioClip[] GetStemsByRole(string role)
        {
            switch (role.ToLower())
            {
${generateRoleSwitchCases(bundle)}
                default:
                    return new AudioClip[0];
            }
        }
    }
}
`;
}

function generateRoleSwitchCases(bundle: StemBundle): string {
  const roleGroups: Record<string, string[]> = {};

  for (const stem of bundle.stems) {
    const role = bundle.manifest.stems.find((s) => s.type === stem.stemType)?.role || "accent";
    if (!roleGroups[role]) roleGroups[role] = [];
    roleGroups[role].push(`${stem.stemType}Stem`);
  }

  return Object.entries(roleGroups)
    .map(
      ([role, stems]) =>
        `                case "${role}":\n                    return new AudioClip[] { ${stems.join(", ")} };`
    )
    .join("\n");
}

// ==================== Helpers ====================

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}
